# netlify.toml

[build]
  # This is the crucial change. Run the full build script.
  command = "npm run build"
  
  # This is where your serverless function will be after the build.
  # It matches your `build:server` output directory.
  functions = "dist/server"
  
  # This is where your built frontend is located.
  # It matches your `build:client` output directory.
  publish = "dist" 

# Your redirect rule is correct and will now work because
# the `functions` directory above is pointed to the right place.
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/node-build/:splat" # The function name is the file name
  status = 200